Improve `fromString` to read time series with missing values
carldata/timeseries pull request #123
Opened 2019-09-14 06:03 UTC by alexander-myltsev

2019-09-18 11:42 UTC, alexander-myltsev commented
@wenta please, start from that PR

2019-09-18 18:41 UTC, wenta commented
Tests failing on my machine, I will finish review when I figure out what is going on.

2019-09-19 06:59 UTC, alexander-myltsev commented
@wenta , `sbt clean test` maybe? :) Please, also fix Travis config if needed.

2019-09-19 07:12 UTC, wenta commented
`sbt clean test` didn't help. btw only this new tests for Csv failed

2019-09-19 10:13 UTC, alexander-myltsev commented
What's the error message?

2019-09-19 10:46 UTC, wenta commented
it fails because of this: ```throw new IllegalArgumentException("Wrong input string format"```
for example:
``` - should read single series from string *** FAILED ***
[info]   java.lang.IllegalArgumentException: Wrong input string format
[info]   at carldata.series.Csv$.fromString(Csv.scala:50)
[info]   at carldata.series.CsvTest.$anonfun$new$1(CsvTest.scala:17)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)```

2019-09-19 10:49 UTC, wenta requested changes

2019-09-19 10:49 UTC, wenta commented on shared/src/main/scala/carldata/series/Csv.scala
> +    require(lines.nonEmpty)
I think it is better to return empty sequence if lines are empty.

2019-09-19 10:49 UTC, wenta commented on shared/src/main/scala/carldata/series/Csv.scala
> +    require(tss.nonEmpty)
Why throwing exception on empty Seq? I think it is bad for production code. Just return empty string if tss.isEmpty.

2019-09-19 10:49 UTC, wenta commented on shared/src/main/scala/carldata/series/Csv.scala
> +    val header = lines.head
`header` is used only once, there is no need to create new value

2019-09-19 10:49 UTC, wenta commented on shared/src/main/scala/carldata/series/Csv.scala
> +    val columnsCount = header.split(tokensDelimeter) match {
This is too complicated. Please use just `val columnsCount = header.split(tokensDelimeter).length` for now.

2019-09-19 10:49 UTC, wenta commented on shared/src/main/scala/carldata/series/Csv.scala
> +    val data = Vector.fill(valueColumnsCount)(ArrayBuffer.empty[(Long, Double)])
I think we do not have to use mutable ArrayBuffer if `data` is result of recursive function.

2019-10-20 18:56 UTC, closed without merging